### ISSUE TITLE
Замечания по коду

### ISSUE THREAD

**Issue by roman-bodavskiy** [Shamillion/echo-bot#4]
```
    showLevel val = case val of
      DEBUG -> "DEBUG  "
      INFO -> "INFO   "
      WARNING -> "WARNING"
      ERROR -> "ERROR  "
```
А почему здесь нельзя использовать просто `show val`?

**Comment by roman-bodavskiy** [comment]
`sandRepeatsH` опечатка

**Comment by roman-bodavskiy** [comment]
`print ("Trying to set a connection... " :: String)`

это то же что `putStrLn`

**Comment by Shamillion** [comment]
> ```
>     showLevel val = case val of
>       DEBUG -> "DEBUG  "
>       INFO -> "INFO   "
>       WARNING -> "WARNING"
>       ERROR -> "ERROR  "
> ```
> 
> А почему здесь нельзя использовать просто `show val`?

Разное количество пробелов после названия приоритета, необходимых для унификации отображения заголовка строк в логах.  `show val` можно использовать , но это сделает вывод менее красивым

**Comment by Shamillion** [comment]
> ```
>     showLevel val = case val of
>       DEBUG -> "DEBUG  "
>       INFO -> "INFO   "
>       WARNING -> "WARNING"
>       ERROR -> "ERROR  "
> ```
> 
> А почему здесь нельзя использовать просто `show val`?

Разное количество пробелов после названия приоритета, необходимых для унификации отображения заголовка строк в логах.  `show val` можно использовать , но это сделает вывод менее красивым
